### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by Frontrider** [HxGodot/HxGodot.github.io#1]
Title says all, I clicked the discord invite on the page and was greeted with the issue.
https://discord.com/invite/Uqh2Czx7
![image](https://user-images.githubusercontent.com/6755034/213926750-4291cf93-cfb0-42bb-a3a2-54112cd7f7ce.png)

**Comment by dazKind** [comment]
Hi there!
Yes, you are right. The link was only for 7 days valid. 
I created a new one that hopefully wont time out anymore: https://discord.gg/a3u9QPUHdg
